### ISSUE TITLE
Spinning while waiting for active map reset

### ISSUE THREAD

**Issue by ethanseq** [Soldann/MORB_SLAM#62]
When the the slamming algorithm gets lost, it sometimes gets stuck when trying to reset the map. It is currently suspected  that it is getting stuck in a spin lock.

**Comment by Ryan-Red** [comment]
```
IMU is not or recently initialized. Reseting active map...
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
^C--Type <RET> for more, q to quit, c to continue without paging--c

Thread 1 "stereo_inertial" received signal SIGINT, Interrupt.
0x00007ffff358423f in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7ffffffd81b0, rem=rem@entry=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
78      ../sysdeps/unix/sysv/linux/clock_nanosleep.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff358423f in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7ffffffd81b0, rem=rem@entry=0x0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007ffff3589ec7 in __GI___nanosleep (requested_time=requested_time@entry=0x7ffffffd81b0, remaining=remaining@entry=0x0) at nanosleep.c:27
#2  0x00007ffff35bc85f in usleep (useconds=useconds@entry=3000) at ../sysdeps/posix/usleep.c:32
#3  0x00007ffff7deb607 in ORB_SLAM3::LoopClosing::RequestResetActiveMap(ORB_SLAM3::Map*) (this=0x555593a9b150, pMap=0x5555702ed9f0)
    at /home/ryan/MartinRea/MORB_SLAM/src/LoopClosing.cc:2262
#4  0x00007ffff7dcc49d in ORB_SLAM3::Tracking::ResetActiveMap(bool) (this=0x555593a2b9f0, bLocMap=bLocMap@entry=false)
    at /home/ryan/MartinRea/MORB_SLAM/src/Tracking.cc:3629
#5  0x00007ffff7d8332e in ORB_SLAM3::System::TrackStereo(cv::Mat const&, cv::Mat const&, double const&, std::vector<ORB_SLAM3::IMU::Point, std::allocator<ORB_SLAM3::IMU::Point> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    (this=0x7fffffffd5c0, imLeft=..., imRight=..., timestamp=@0x7fffffffceb8: 1657818009.2826099, vImuMeas=std::vector of length 7, capacity 128 = {...}, fi--Type <RET> for more, q to quit, c to continue without paging--c
lename="") at /home/ryan/MartinRea/MORB_SLAM/src/System.cc:317
#6  0x0000555555565e6a in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/9/bits/basic_string.h:267
(gdb) 
```

**Comment by Ryan-Red** [comment]
See: https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/346
